import { Admin } from './Admin'
import { Role } from './Role'
import { Translation } from './Translation'
import { Slider } from './Slider'
import { Social } from './Social'
import { Page } from './Page'
import { Menu } from './Menu'
import { Language } from './Language'
import { Section } from './Section'
import { Ticket } from './Ticket'
import { Department } from './Department'
import { Message } from './Message'
import { TicketMessage } from './TicketMessage'

export { Admin, Role, Translation, Slider, Social, Page, Menu, Language, Section, Ticket, Department, Message, TicketMessage }
