
export enum reactionType {
    OUTPUT_MANAGEMENT_RELAY_MODULE = 'OUTPUT_MANAGEMENT_RELAY_MODULE',
    MANAGEMENT_OF_OUTPUT_CONTROLLERS = 'MANAGEMENT_OF_OUTPUT_CONTROLLERS',
    MANAGEMENT_OF_ACCESS_POINTS = 'MANAGEMENT_OF_ACCESS_POINTS',
  }
